name: "Migrate tracks for apps"

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  migrate-tracks:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1
      - uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "Altinn AI [Bot]"
          git config --global user.email "noreply-test-ai@digdir.no"

      - name: Install deps
        run: bun install --production --no-save

      - name: create working directory
        run: mkdir -p apps

      - name: Run migration script
        working-directory: ./apps
        env:
          OPEN_API_KEY: ${{ secrets.OPEN_API_KEY }}
          OPEN_AI_MODEL: ${{ secrets.OPEN_AI_MODEL }}
          OPEN_AI_API_VERSION: ${{ secrets.OPEN_AI_API_VERSION }}
          OPEN_AI_API_ENDPOINT: ${{ secrets.OPEN_AI_API_ENDPOINT }}
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
          GITEA_BASE_URL: ${{ secrets.GITEA_BASE_URL }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PW: ${{ secrets.DB_PW }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: bun run ../src/index.ts --path App

      - name: Test result
        working-directory: ./apps
        run: ls -al && cd newcomer-sogndal && git status
